"""create mills table and mill foreign keys

Revision ID: 03ff9a0f81e0
Revises: 6fbe743eec75
Create Date: 2026-09-04 16:08:22.875696

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "03ff9a0f81e0"
down_revision: str | Sequence[str] | None = "6fbe743eec75"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _backfill_mills_from_existing_tenant_rows() -> None:
    """Mint a loudly synthetic mills row for every mill_id already referenced
    by households or batches, so the two foreign keys can be added without a
    ForeignKeyViolation.

    A no-op on an empty database, which is the expected case. Written anyway
    because `docker compose down -v` is documented but not enforced (a stale
    local volume is likely), because it makes downgrade->upgrade round-trips
    idempotent — the test suite does exactly that on every run — and because a
    hard failure on upgrade is a worse outcome than 20 lines of SQL. Note that
    90543b394721 set a precedent of *not* backfilling; do not copy it here,
    where the new constraint can actually reject existing rows.

    Written as INSERT ... SELECT rather than the sa.table() + op.bulk_insert
    seeding precedent at 67ca06521be2: that one inserts known constant rows,
    whereas these are derived from existing data, and the explicit
    ::malaysia_state cast avoids bulk_insert binding the enum column as
    varchar (which Postgres will not implicitly coerce).

    `state` is the one fabricated value — nothing in households or batches can
    derive it. Every other column is unmistakably synthetic, and a permanently
    nullable state column costs more than it buys.
    """
    op.execute(
        sa.text(
            """
            INSERT INTO mills (
                id, name, mpob_licence_number, postal_address, email, district, state
            )
            SELECT
                referenced.mill_id,
                'Unregistered mill ' || left(referenced.mill_id::text, 8),
                'UNREGISTERED-' || referenced.mill_id::text,
                'UNKNOWN - backfilled by migration 03ff9a0f81e0',
                'unknown-' || left(referenced.mill_id::text, 8) || '@tapak.invalid',
                'UNKNOWN',
                'sabah'::malaysia_state
            FROM (
                SELECT mill_id FROM households
                UNION
                SELECT mill_id FROM batches
            ) AS referenced
            WHERE NOT EXISTS (SELECT 1 FROM mills WHERE mills.id = referenced.mill_id)
            """
        )
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mills",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("mpob_licence_number", sa.String(length=64), nullable=False),
        sa.Column("postal_address", sa.String(length=500), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("district", sa.String(length=255), nullable=False),
        # create_type=False is mandatory: malaysia_state already exists from
        # 67ca06521be2. Precedent for reusing an enum is 6fbe743eec75.
        sa.Column(
            "state",
            postgresql.ENUM("sabah", "sarawak", name="malaysia_state", create_type=False),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mpob_licence_number", name="uq_mills_mpob_licence_number"),
    )
    # ### end Alembic commands ###

    # Hand-written, and order-critical: must run after mills exists and before
    # the foreign keys below, or any pre-existing row would violate them.
    _backfill_mills_from_existing_tenant_rows()

    # No ondelete: RESTRICT, not CASCADE — deleting a mill must never cascade
    # away a five-year evidence trail (Articles 9(1), 4(3), 12(5)).
    op.create_foreign_key("fk_households_mill", "households", "mills", ["mill_id"], ["id"])
    op.create_foreign_key("fk_batches_mill", "batches", "mills", ["mill_id"], ["id"])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_batches_mill", "batches", type_="foreignkey")
    op.drop_constraint("fk_households_mill", "households", type_="foreignkey")
    op.drop_table("mills")
    # ### end Alembic commands ###
    # Do NOT drop the malaysia_state enum: land_document_rules still owns it at
    # this point in the chain, and the suite's downgrade("base") teardown would
    # break. Only a migration that *created* an enum may drop it.
