"""create gap assessment tables

Revision ID: 31848782a044
Revises:
Create Date: 2026-08-15 10:48:52.549965

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "31848782a044"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "households",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mill_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "mill_id", name="uq_households_id_mill_id"),
    )
    op.create_index("ix_households_mill_id", "households", ["mill_id"], unique=False)
    op.create_table(
        "gap_assessments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mill_id", sa.UUID(), nullable=False),
        sa.Column("household_id", sa.UUID(), nullable=False),
        sa.Column("assessed_by", sa.String(length=255), nullable=False),
        sa.Column(
            "assessed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["household_id", "mill_id"],
            ["households.id", "households.mill_id"],
            name="fk_gap_assessments_household_mill",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", name="uq_gap_assessments_household_id"),
        sa.UniqueConstraint("id", "mill_id", name="uq_gap_assessments_id_mill_id"),
    )
    op.create_index("ix_gap_assessments_mill_id", "gap_assessments", ["mill_id"], unique=False)
    op.create_table(
        "gap_assessment_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mill_id", sa.UUID(), nullable=False),
        sa.Column("gap_assessment_id", sa.UUID(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "product_quantity",
                "geolocation",
                "land_ownership",
                "deforestation_proof",
                "labour_consent",
                "documentation_pack",
                name="evidence_category",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("present", "missing", "needs_verification", name="gap_status"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["gap_assessment_id", "mill_id"],
            ["gap_assessments.id", "gap_assessments.mill_id"],
            name="fk_gap_assessment_items_assessment_mill",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "gap_assessment_id", "category", name="uq_gap_assessment_items_assessment_category"
        ),
    )
    op.create_index(
        "ix_gap_assessment_items_mill_id", "gap_assessment_items", ["mill_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_gap_assessment_items_mill_id", table_name="gap_assessment_items")
    op.drop_table("gap_assessment_items")
    op.drop_index("ix_gap_assessments_mill_id", table_name="gap_assessments")
    op.drop_table("gap_assessments")
    op.drop_index("ix_households_mill_id", table_name="households")
    op.drop_table("households")
    # ### end Alembic commands ###
    # Postgres enum types survive their owning column being dropped; remove
    # them explicitly so a downgrade+upgrade cycle doesn't hit "type already exists".
    sa.Enum(name="gap_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="evidence_category").drop(op.get_bind(), checkfirst=True)
