"""create field verification and yield licence check tables

Revision ID: 413978e0a487
Revises: 91a6c56fbc18
Create Date: 2026-08-18 11:31:03.587198

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "413978e0a487"
down_revision: str | Sequence[str] | None = "91a6c56fbc18"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "yield_licence_checks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mill_id", sa.UUID(), nullable=False),
        sa.Column("household_id", sa.UUID(), nullable=False),
        sa.Column("mpob_licensed_area_ha", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("declared_area_ha", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("annual_output_kg", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "regional_yield_benchmark_kg_per_ha", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("licence_mismatch", sa.Boolean(), nullable=False),
        sa.Column("yield_mismatch", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("cleared", "needs_review", name="field_verification_status"),
            nullable=False,
        ),
        sa.Column("recorded_by", sa.String(length=255), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["household_id", "mill_id"],
            ["households.id", "households.mill_id"],
            name="fk_yield_licence_checks_household_mill",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", name="uq_yield_licence_checks_household_id"),
        sa.UniqueConstraint("id", "mill_id", name="uq_yield_licence_checks_id_mill_id"),
    )
    op.create_index(
        "ix_yield_licence_checks_mill_id", "yield_licence_checks", ["mill_id"], unique=False
    )
    op.create_table(
        "field_verification_checks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mill_id", sa.UUID(), nullable=False),
        sa.Column("plot_id", sa.UUID(), nullable=False),
        sa.Column("gnss_checkin_lat", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("gnss_checkin_lon", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("gnss_checkin_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("photo_lat", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("photo_lon", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("photo_taken_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title_area_ha", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("checkin_mismatch", sa.Boolean(), nullable=False),
        sa.Column("photo_mismatch", sa.Boolean(), nullable=False),
        sa.Column("area_mismatch", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("cleared", "needs_review", name="field_verification_status"),
            nullable=False,
        ),
        sa.Column("recorded_by", sa.String(length=255), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plot_id", "mill_id"],
            ["plots.id", "plots.mill_id"],
            name="fk_field_verification_checks_plot_mill",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "mill_id", name="uq_field_verification_checks_id_mill_id"),
        sa.UniqueConstraint("plot_id", name="uq_field_verification_checks_plot_id"),
    )
    op.create_index(
        "ix_field_verification_checks_mill_id",
        "field_verification_checks",
        ["mill_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_field_verification_checks_mill_id", table_name="field_verification_checks")
    op.drop_table("field_verification_checks")
    op.drop_index("ix_yield_licence_checks_mill_id", table_name="yield_licence_checks")
    op.drop_table("yield_licence_checks")
    # ### end Alembic commands ###
    # Postgres enum types survive their owning columns being dropped; remove
    # them explicitly so a downgrade+upgrade cycle doesn't hit "type already exists".
    sa.Enum(name="field_verification_status").drop(op.get_bind(), checkfirst=True)
