"""create rules engine tables

Revision ID: 67ca06521be2
Revises: 31848782a044
Create Date: 2026-08-15 16:19:20.413214

"""

import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67ca06521be2"
down_revision: str | Sequence[str] | None = "31848782a044"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

RULE_VERSION = "sabah-sarawak-v1"

# (state, land_type) -> [(document_type, is_hard_fail), ...]
# Sourced from tech.md §6.3.1's Land Document Playbook table. The only
# hard-fail condition the roadmap doc calls out is leased land without a
# tenancy agreement ("this cannot be silently skipped") — every other
# missing document resolves to needs_follow_up rather than failed.
RULE_REQUIREMENTS: dict[tuple[str, str], list[tuple[str, bool]]] = {
    ("sabah", "native_title"): [("sabah_native_title", False)],
    ("sabah", "country_lease"): [("sabah_country_lease", False)],
    ("sabah", "field_register"): [("sabah_field_register", False)],
    ("sarawak", "provisional_lease"): [("sarawak_provisional_lease", False)],
    ("sarawak", "native_customary_rights"): [("jabatan_tanah_survei_permission", False)],
    ("sabah", "leased"): [
        ("tenancy_agreement", True),
        ("landlord_identity", False),
        ("landlord_title", False),
    ],
    ("sarawak", "leased"): [
        ("tenancy_agreement", True),
        ("landlord_identity", False),
        ("landlord_title", False),
    ],
    ("sabah", "untransferred_inheritance"): [("co_owner_list", False)],
    ("sarawak", "untransferred_inheritance"): [("co_owner_list", False)],
    ("sabah", "scheme_land"): [("settler_agreement", False), ("scheme_number", False)],
    ("sarawak", "scheme_land"): [("settler_agreement", False), ("scheme_number", False)],
}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "land_document_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("rule_version", sa.String(length=50), nullable=False),
        sa.Column("state", sa.Enum("sabah", "sarawak", name="malaysia_state"), nullable=False),
        sa.Column(
            "land_type",
            sa.Enum(
                "native_title",
                "country_lease",
                "field_register",
                "provisional_lease",
                "native_customary_rights",
                "leased",
                "untransferred_inheritance",
                "scheme_land",
                name="land_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "rule_version", "state", "land_type", name="uq_land_document_rules_version_state_type"
        ),
    )
    op.create_table(
        "land_document_rule_requirements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum(
                "sabah_native_title",
                "sabah_country_lease",
                "sabah_field_register",
                "sarawak_provisional_lease",
                "jabatan_tanah_survei_permission",
                "tenancy_agreement",
                "landlord_identity",
                "landlord_title",
                "co_owner_list",
                "settler_agreement",
                "scheme_number",
                name="document_type",
            ),
            nullable=False,
        ),
        sa.Column("is_hard_fail", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["land_document_rules.id"],
            name="fk_land_document_rule_requirements_rule",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "rule_id", "document_type", name="uq_land_document_rule_requirements_rule_document"
        ),
    )
    op.create_table(
        "land_ownership_assessments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mill_id", sa.UUID(), nullable=False),
        sa.Column("household_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.Enum("sabah", "sarawak", name="malaysia_state"), nullable=False),
        sa.Column(
            "land_type",
            sa.Enum(
                "native_title",
                "country_lease",
                "field_register",
                "provisional_lease",
                "native_customary_rights",
                "leased",
                "untransferred_inheritance",
                "scheme_land",
                name="land_type",
            ),
            nullable=False,
        ),
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("cleared", "failed", "needs_follow_up", name="land_ownership_status"),
            nullable=False,
        ),
        sa.Column("assessed_by", sa.String(length=255), nullable=False),
        sa.Column(
            "assessed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["household_id", "mill_id"],
            ["households.id", "households.mill_id"],
            name="fk_land_ownership_assessments_household_mill",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"], ["land_document_rules.id"], name="fk_land_ownership_assessments_rule"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", name="uq_land_ownership_assessments_household_id"),
        sa.UniqueConstraint("id", "mill_id", name="uq_land_ownership_assessments_id_mill_id"),
    )
    op.create_index(
        "ix_land_ownership_assessments_mill_id",
        "land_ownership_assessments",
        ["mill_id"],
        unique=False,
    )
    op.create_table(
        "land_ownership_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mill_id", sa.UUID(), nullable=False),
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum(
                "sabah_native_title",
                "sabah_country_lease",
                "sabah_field_register",
                "sarawak_provisional_lease",
                "jabatan_tanah_survei_permission",
                "tenancy_agreement",
                "landlord_identity",
                "landlord_title",
                "co_owner_list",
                "settler_agreement",
                "scheme_number",
                name="document_type",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id", "mill_id"],
            ["land_ownership_assessments.id", "land_ownership_assessments.mill_id"],
            name="fk_land_ownership_documents_assessment_mill",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "assessment_id", "document_type", name="uq_land_ownership_documents_assessment_type"
        ),
    )
    op.create_index(
        "ix_land_ownership_documents_mill_id", "land_ownership_documents", ["mill_id"], unique=False
    )
    # ### end Alembic commands ###

    _seed_land_document_rules()


def _seed_land_document_rules() -> None:
    """Populate the sabah-sarawak-v1 rule set (tech.md §6.3.1)."""
    rules_table = sa.table(
        "land_document_rules",
        sa.column("id", sa.UUID()),
        sa.column("rule_version", sa.String()),
        sa.column("state", sa.Enum("sabah", "sarawak", name="malaysia_state", create_type=False)),
        sa.column(
            "land_type",
            sa.Enum(
                "native_title",
                "country_lease",
                "field_register",
                "provisional_lease",
                "native_customary_rights",
                "leased",
                "untransferred_inheritance",
                "scheme_land",
                name="land_type",
                create_type=False,
            ),
        ),
    )
    requirements_table = sa.table(
        "land_document_rule_requirements",
        sa.column("id", sa.UUID()),
        sa.column("rule_id", sa.UUID()),
        sa.column(
            "document_type",
            sa.Enum(
                "sabah_native_title",
                "sabah_country_lease",
                "sabah_field_register",
                "sarawak_provisional_lease",
                "jabatan_tanah_survei_permission",
                "tenancy_agreement",
                "landlord_identity",
                "landlord_title",
                "co_owner_list",
                "settler_agreement",
                "scheme_number",
                name="document_type",
                create_type=False,
            ),
        ),
        sa.column("is_hard_fail", sa.Boolean()),
    )

    rule_rows = []
    requirement_rows = []
    for (state, land_type), requirements in RULE_REQUIREMENTS.items():
        rule_id = uuid.uuid4()
        rule_rows.append(
            {"id": rule_id, "rule_version": RULE_VERSION, "state": state, "land_type": land_type}
        )
        for document_type, is_hard_fail in requirements:
            requirement_rows.append(
                {
                    "id": uuid.uuid4(),
                    "rule_id": rule_id,
                    "document_type": document_type,
                    "is_hard_fail": is_hard_fail,
                }
            )

    op.bulk_insert(rules_table, rule_rows)
    op.bulk_insert(requirements_table, requirement_rows)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_land_ownership_documents_mill_id", table_name="land_ownership_documents")
    op.drop_table("land_ownership_documents")
    op.drop_index("ix_land_ownership_assessments_mill_id", table_name="land_ownership_assessments")
    op.drop_table("land_ownership_assessments")
    op.drop_table("land_document_rule_requirements")
    op.drop_table("land_document_rules")
    # ### end Alembic commands ###
    # Postgres enum types survive their owning column being dropped; remove
    # them explicitly so a downgrade+upgrade cycle doesn't hit "type already exists".
    sa.Enum(name="land_ownership_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="document_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="land_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="malaysia_state").drop(op.get_bind(), checkfirst=True)
