"""create national systems lookup table

Revision ID: 6fbe743eec75
Revises: 90543b394721
Create Date: 2026-08-19 21:19:26.292005

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6fbe743eec75"
down_revision: str | Sequence[str] | None = "90543b394721"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "national_systems_lookups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mill_id", sa.UUID(), nullable=False),
        sa.Column("household_id", sa.UUID(), nullable=False),
        sa.Column("mpob_licence_number", sa.String(length=64), nullable=False),
        sa.Column("sims_transaction_volume_kg", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("declared_area_ha", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column(
            "regional_yield_benchmark_kg_per_ha", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("volume_yield_mismatch", sa.Boolean(), nullable=False),
        sa.Column("geosawit_mapping_exists", sa.Boolean(), nullable=False),
        sa.Column("geosawit_reference", sa.String(length=255), nullable=True),
        sa.Column("emspo_certification_status", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "cleared", "needs_review", name="field_verification_status", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("looked_up_by", sa.String(length=255), nullable=False),
        sa.Column(
            "looked_up_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["household_id", "mill_id"],
            ["households.id", "households.mill_id"],
            name="fk_national_systems_lookups_household_mill",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", name="uq_national_systems_lookups_household_id"),
        sa.UniqueConstraint("id", "mill_id", name="uq_national_systems_lookups_id_mill_id"),
    )
    op.create_index(
        "ix_national_systems_lookups_mill_id", "national_systems_lookups", ["mill_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_national_systems_lookups_mill_id", table_name="national_systems_lookups")
    op.drop_table("national_systems_lookups")
    # ### end Alembic commands ###
