"""add household contact fields and create batch and evidence pack tables

Revision ID: 90543b394721
Revises: 413978e0a487
Create Date: 2026-08-18 17:17:07.399472

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "90543b394721"
down_revision: str | Sequence[str] | None = "413978e0a487"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "batches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mill_id", sa.UUID(), nullable=False),
        sa.Column("product_description", sa.String(length=255), nullable=False),
        sa.Column("trade_name", sa.String(length=255), nullable=False),
        sa.Column("hs_code", sa.String(length=20), nullable=False),
        sa.Column("net_mass_kg", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("recipient_name", sa.String(length=255), nullable=False),
        sa.Column("recipient_postal_address", sa.String(length=500), nullable=False),
        sa.Column("recipient_email", sa.String(length=255), nullable=False),
        sa.Column(
            "no_mixing_status",
            sa.Enum("single_source", "mixed_sources", name="no_mixing_status"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "mill_id", name="uq_batches_id_mill_id"),
    )
    op.create_index("ix_batches_mill_id", "batches", ["mill_id"], unique=False)
    op.create_table(
        "evidence_packs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mill_id", sa.UUID(), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("assembled_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("geojson", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("generated_by", sa.String(length=255), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["batch_id", "mill_id"],
            ["batches.id", "batches.mill_id"],
            name="fk_evidence_packs_batch_mill",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", name="uq_evidence_packs_batch_id"),
        sa.UniqueConstraint("id", "mill_id", name="uq_evidence_packs_id_mill_id"),
    )
    op.create_index("ix_evidence_packs_mill_id", "evidence_packs", ["mill_id"], unique=False)
    op.create_table(
        "batch_plots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mill_id", sa.UUID(), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("plot_id", sa.UUID(), nullable=False),
        sa.Column("harvest_date", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["batch_id", "mill_id"],
            ["batches.id", "batches.mill_id"],
            name="fk_batch_plots_batch_mill",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plot_id", "mill_id"],
            ["plots.id", "plots.mill_id"],
            name="fk_batch_plots_plot_mill",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", "plot_id", name="uq_batch_plots_batch_id_plot_id"),
        sa.UniqueConstraint("id", "mill_id", name="uq_batch_plots_id_mill_id"),
    )
    op.create_index("ix_batch_plots_mill_id", "batch_plots", ["mill_id"], unique=False)
    op.add_column("households", sa.Column("postal_address", sa.String(length=500), nullable=False))
    op.add_column("households", sa.Column("email", sa.String(length=255), nullable=False))
    op.add_column("households", sa.Column("district", sa.String(length=255), nullable=False))
    op.add_column(
        "households",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("households", "updated_at")
    op.drop_column("households", "district")
    op.drop_column("households", "email")
    op.drop_column("households", "postal_address")
    op.drop_index("ix_batch_plots_mill_id", table_name="batch_plots")
    op.drop_table("batch_plots")
    op.drop_index("ix_evidence_packs_mill_id", table_name="evidence_packs")
    op.drop_table("evidence_packs")
    op.drop_index("ix_batches_mill_id", table_name="batches")
    op.drop_table("batches")
    # ### end Alembic commands ###
    # Postgres enum types survive their owning column being dropped; remove
    # them explicitly so a downgrade+upgrade cycle doesn't hit "type already exists".
    sa.Enum(name="no_mixing_status").drop(op.get_bind(), checkfirst=True)
