"""create plot and deforestation check tables

Revision ID: 91a6c56fbc18
Revises: 999339292010
Create Date: 2026-08-16 17:14:40.914407

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "91a6c56fbc18"
down_revision: str | Sequence[str] | None = "999339292010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mill_id", sa.UUID(), nullable=False),
        sa.Column("household_id", sa.UUID(), nullable=False),
        sa.Column("polygon", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("centroid_lat", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("centroid_lon", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("area_ha", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("collected_by", sa.String(length=255), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["household_id", "mill_id"],
            ["households.id", "households.mill_id"],
            name="fk_plots_household_mill",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "mill_id", name="uq_plots_id_mill_id"),
    )
    op.create_index("ix_plots_mill_id", "plots", ["mill_id"], unique=False)
    op.create_table(
        "deforestation_checks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mill_id", sa.UUID(), nullable=False),
        sa.Column("plot_id", sa.UUID(), nullable=False),
        sa.Column("forest_area_ha", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("tree_height_m", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("canopy_cover_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("predominantly_agricultural_or_urban", sa.Boolean(), nullable=False),
        sa.Column("pre_2020_imagery_date", sa.Date(), nullable=False),
        sa.Column("post_2020_imagery_date", sa.Date(), nullable=False),
        sa.Column("forest_loss_detected", sa.Boolean(), nullable=False),
        sa.Column("review_inconclusive", sa.Boolean(), nullable=False),
        sa.Column("reviewed_by", sa.String(length=255), nullable=False),
        sa.Column(
            "reviewed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("compliant", "non_compliant", "needs_review", name="deforestation_status"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plot_id", "mill_id"],
            ["plots.id", "plots.mill_id"],
            name="fk_deforestation_checks_plot_mill",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "mill_id", name="uq_deforestation_checks_id_mill_id"),
        sa.UniqueConstraint("plot_id", name="uq_deforestation_checks_plot_id"),
    )
    op.create_index(
        "ix_deforestation_checks_mill_id", "deforestation_checks", ["mill_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_deforestation_checks_mill_id", table_name="deforestation_checks")
    op.drop_table("deforestation_checks")
    op.drop_index("ix_plots_mill_id", table_name="plots")
    op.drop_table("plots")
    # ### end Alembic commands ###
    # Postgres enum types survive their owning column being dropped; remove
    # them explicitly so a downgrade+upgrade cycle doesn't hit "type already exists".
    sa.Enum(name="deforestation_status").drop(op.get_bind(), checkfirst=True)
