"""create labour declaration tables

Revision ID: 999339292010
Revises: 67ca06521be2
Create Date: 2026-08-16 11:00:12.061966

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "999339292010"
down_revision: str | Sequence[str] | None = "67ca06521be2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consent_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mill_id", sa.UUID(), nullable=False),
        sa.Column("household_id", sa.UUID(), nullable=False),
        sa.Column("mykad_last4", sa.String(length=4), nullable=False),
        sa.Column("credit_referral_consent_given", sa.Boolean(), nullable=False),
        sa.Column(
            "signature_method",
            sa.Enum("signature", "thumbprint", name="signature_method"),
            nullable=False,
        ),
        sa.Column("collected_by", sa.String(length=255), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["household_id", "mill_id"],
            ["households.id", "households.mill_id"],
            name="fk_consent_records_household_mill",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", name="uq_consent_records_household_id"),
        sa.UniqueConstraint("id", "mill_id", name="uq_consent_records_id_mill_id"),
    )
    op.create_index("ix_consent_records_mill_id", "consent_records", ["mill_id"], unique=False)
    op.create_table(
        "labour_declarations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mill_id", sa.UUID(), nullable=False),
        sa.Column("household_id", sa.UUID(), nullable=False),
        sa.Column("labour_arrangement_description", sa.Text(), nullable=False),
        sa.Column("no_child_labour_confirmed", sa.Boolean(), nullable=False),
        sa.Column("has_land_dispute", sa.Boolean(), nullable=False),
        sa.Column("land_dispute_notes", sa.Text(), nullable=True),
        sa.Column(
            "signature_method",
            sa.Enum("signature", "thumbprint", name="signature_method"),
            nullable=False,
        ),
        sa.Column("collected_by", sa.String(length=255), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["household_id", "mill_id"],
            ["households.id", "households.mill_id"],
            name="fk_labour_declarations_household_mill",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", name="uq_labour_declarations_household_id"),
        sa.UniqueConstraint("id", "mill_id", name="uq_labour_declarations_id_mill_id"),
    )
    op.create_index(
        "ix_labour_declarations_mill_id", "labour_declarations", ["mill_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_labour_declarations_mill_id", table_name="labour_declarations")
    op.drop_table("labour_declarations")
    op.drop_index("ix_consent_records_mill_id", table_name="consent_records")
    op.drop_table("consent_records")
    # ### end Alembic commands ###
    # Postgres enum types survive their owning column being dropped; remove
    # them explicitly so a downgrade+upgrade cycle doesn't hit "type already exists".
    sa.Enum(name="signature_method").drop(op.get_bind(), checkfirst=True)
