"""create users table

Revision ID: f116d4e69397
Revises: 03ff9a0f81e0
Create Date: 2026-09-04 16:15:46.643808

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f116d4e69397"
down_revision: str | Sequence[str] | None = "03ff9a0f81e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        # user_role is new in this revision, so it is created here (no
        # create_type=False) — and must therefore be dropped in downgrade().
        sa.Column("role", sa.Enum("admin", "mill_user", name="user_role"), nullable=False),
        sa.Column("mill_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(role = 'admin' AND mill_id IS NULL) OR (role = 'mill_user' AND mill_id IS NOT NULL)",
            name="ck_users_role_mill_id",
        ),
        sa.ForeignKeyConstraint(["mill_id"], ["mills.id"], name="fk_users_mill"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_index("ix_users_mill_id", "users", ["mill_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_mill_id", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
    # A Postgres enum type outlives the column that used it, so this revision
    # must drop what it created or a downgrade->upgrade round-trip fails on
    # "type user_role already exists" — which the suite's downgrade("base")
    # teardown does on every run. Precedent: 31848782a044. The contrasting
    # case is 03ff9a0f81e0, which *reuses* malaysia_state and must not drop it.
    sa.Enum(name="user_role").drop(op.get_bind(), checkfirst=True)
